name: Post Welcome Comment By NKS
on: 
  pull_request:
    types: [opened] 
jobs:
  build:
    name: Post Welcome comment
    runs-on: ubuntu-latest
      steps:
      - run: gh pr comment $PR_URL --body "Welcome to the repository!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
